"""Issue 009 — 2025-12-19. The feedback loop tightens."""

URL = "https://theinnermostloop.substack.com/p/welcome-to-december-19-2025"
B = "https://nicholsn.github.io/innermost-loop-kb/"

SPEC = {
    "issue": {
        "date": "2025-12-19",
        "title": "Welcome to December 19, 2025",
        "url": URL,
        "thesis": "The feedback loop is tightening faster than we can measure.",
        "body": """
# Welcome to December 19, 2025

Noam Shazeer puts it at 50/50 that the next major breakthrough comes from Gemini
rather than a human researcher. Four days earlier the corpus recorded a model
watching its own training runs; this is the same claim stated as a probability.

The counterweight is friction. The Gemini 3 team now *rejects* performance gains
that exceed a complexity budget, protecting the throughput of 150 researchers
over isolated metrics — capability traded away deliberately.
""",
    },
    "themes": [
        {"id": "data-beyond-text", "type": "Theme",
         "title": "Grounding in physics, not web text", "first_seen": "2025-12-19",
         "domain": "science",
         "body": "The human-text corpus runs out, so the frontier turns to measurement: "
                 "scientific data at a scale that dwarfs the text internet, promising "
                 "models grounded in the non-negotiable rather than the web's guesses."},
    ],
    "organizations": [
        {"id": "dte-energy", "type": "Organization", "title": "DTE Energy",
         "resource": "https://www.dteenergy.com/", "body": "Michigan utility powering a Stargate site."},
        {"id": "samsung", "type": "Organization", "title": "Samsung",
         "resource": "https://www.samsung.com/", "body": "Memory and SoC manufacturer."},
        {"id": "tae-technologies", "type": "Organization", "title": "TAE Technologies",
         "resource": "https://tae.com/", "body": "Fusion developer."},
        {"id": "rocket-lab", "type": "Organization", "title": "Rocket Lab",
         "resource": "https://www.rocketlabusa.com/", "body": "Small-launch and satellite manufacturer."},
    ],
    "people": [
        {"id": "noam-shazeer", "type": "Person", "title": "Noam Shazeer", "name": "Noam Shazeer",
         "body": "Google AI lead; put even odds on the next breakthrough coming from Gemini."},
    ],
    "systems": [
        {"id": "gpt-5-2-codex", "type": "AISystem", "title": "GPT-5.2-Codex",
         "developed_by": [B + "organizations/openai"], "modality": "code",
         "evaluated_on": [B + "benchmarks/terminal-bench-2"]},
        {"id": "functiongemma", "type": "AISystem", "title": "FunctionGemma",
         "developed_by": [B + "organizations/google"], "modality": "function calling",
         "body": "A 270M model specialized for tool calls — intelligence pushed to the edge."},
        {"id": "genie", "type": "AISystem", "title": "Genie",
         "developed_by": [B + "organizations/google-deepmind"], "modality": "world model"},
        {"id": "sima", "type": "AISystem", "title": "SIMA",
         "developed_by": [B + "organizations/google-deepmind"], "modality": "embodied agent"},
    ],
    "benchmarks": [
        {"id": "terminal-bench-2", "type": "Benchmark", "title": "Terminal Bench 2.0",
         "measures_capability": "completing real tasks in a terminal"},
    ],
    "facilities": [
        {"id": "stargate-michigan", "type": "Facility", "title": "Stargate Michigan",
         "operated_by": [B + "organizations/oracle", B + "organizations/openai"],
         "located_in": "Michigan, USA", "capacity": "1.4 GW"},
        {"id": "genesis-mission", "type": "Facility", "title": "Genesis Mission",
         "operated_by": [B + "organizations/doe"], "located_in": "United States",
         "capacity": "~3,600 PB of scientific data",
         "body": "A corpus of measurement rather than text, estimated to dwarf the "
                 "text-based internet."},
    ],
    "developments": [
        {"id": "2025-12-19-shazeer-5050-gemini-breakthrough",
         "title": "Shazeer puts even odds on Gemini making the next breakthrough",
         "claim": "Google's Noam Shazeer put the odds at 50/50 that the next major AI "
                  "breakthrough will be generated by Gemini rather than a human researcher.",
         "domain": "agents", "actor": ["people/noam-shazeer", "google"], "score": "50/50",
         "evidences": ["recursive-self-improvement"],
         "supersedes": [B + "developments/2025-12-15-codex-babysits-own-training"]},
        {"id": "2025-12-19-deepmind-proto-agi-merge",
         "title": "DeepMind plans to converge its world models into a proto-AGI",
         "claim": "DeepMind plans to merge Nano Banana Pro with its Genie and SIMA world "
                  "models into a converged proto-AGI.",
         "domain": "models", "actor": ["google-deepmind"],
         "about": [B + "systems/genie", B + "systems/sima"],
         "evidences": ["inhabitable-worlds", "network-over-node"]},
        {"id": "2025-12-19-gemini-complexity-budget",
         "title": "The Gemini team rejects gains that exceed a complexity budget",
         "claim": "The Gemini 3 team said it now rejects performance gains that exceed a "
                  "complexity budget, prioritizing the cumulative velocity of 150 researchers "
                  "over isolated metrics.",
         "domain": "models", "actor": ["google"], "score": "150 researchers",
         "body": "Capability deliberately declined to protect throughput — the first time "
                 "the corpus records a lab trading accuracy away on purpose."},
        {"id": "2025-12-19-differentiable-retrieval-pretraining",
         "title": "Google works to make retrieval differentiable in pre-training",
         "claim": "Google is working to make retrieval fully differentiable within "
                  "pre-training, hardwiring the internet into the model itself.",
         "domain": "models", "actor": ["google"], "evidences": ["scaffolding-over-weights"]},
        {"id": "2025-12-19-gpt52-codex-terminal-bench",
         "title": "GPT-5.2-Codex tops Terminal Bench 2.0 and automates the white-hat",
         "claim": "OpenAI released GPT-5.2-Codex, which leads Terminal Bench 2.0 and jumps "
                  "sharply on professional capture-the-flag cybersecurity challenges.",
         "domain": "agents", "actor": ["openai"],
         "about": [B + "systems/gpt-5-2-codex", B + "benchmarks/terminal-bench-2"],
         "evidences": ["autonomy-clock-speed"]},
        {"id": "2025-12-19-functiongemma-edge",
         "title": "FunctionGemma pushes tool use to the network edge",
         "claim": "Google released FunctionGemma, a 270M model fine-tuned for function calling, "
                  "with a recipe for further specialization.",
         "domain": "models", "actor": ["google"], "about": [B + "systems/functiongemma"],
         "evidences": ["network-over-node"]},
        {"id": "2025-12-19-genesis-mission-3600-petabytes",
         "title": "The Genesis Mission could unlock 3,600 petabytes of scientific data",
         "claim": "Third-party analysis estimates the DOE's Genesis Mission could unlock 3,600 "
                  "petabytes of scientific training data, a corpus dwarfing the text internet.",
         "domain": "science", "actor": ["doe"], "score": "3,600 PB",
         "about": [B + "facilities/genesis-mission"],
         "evidences": ["data-beyond-text", "science-as-industrial-policy"],
         "supersedes": [B + "developments/2025-12-13-doe-science-security-platform"]},
        {"id": "2025-12-19-datacenter-investment-61b",
         "title": "A record $61B flowed into datacenters this year",
         "claim": "A record $61 billion flowed into data centers during the year.",
         "domain": "economics", "score": "$61B",
         "evidences": ["compute-capital-stack", "infrastructure-crowding-out"]},
        {"id": "2025-12-19-speed-act-passes-house",
         "title": "The House passes the SPEED Act, cutting NEPA timelines to 150 days",
         "claim": "The House passed the SPEED Act, cutting NEPA litigation timelines from six "
                  "years to 150 days to fast-track AI infrastructure.",
         "domain": "policy", "actor": ["us-congress"], "score": "6 years to 150 days",
         "evidences": ["politics-as-infrastructure", "infrastructure-crowding-out"],
         "supersedes": [B + "developments/2025-12-17-speed-act-permitting"]},
        {"id": "2025-12-19-michigan-stargate-1-4gw",
         "title": "Michigan approves 1.4 GW for an Oracle and OpenAI Stargate site",
         "claim": "Michigan approved DTE Energy to power a 1.4-gigawatt Stargate facility for "
                  "Oracle and OpenAI.",
         "domain": "compute", "actor": ["dte-energy", "oracle", "openai"], "score": "1.4 GW",
         "about": [B + "facilities/stargate-michigan"],
         "evidences": ["compute-capital-stack"]},
        {"id": "2025-12-19-anthropic-2-3gw-bitcoin-miners",
         "title": "Anthropic secures 2.3 GW from repurposed Bitcoin miners",
         "claim": "Anthropic secured 2.3 GW of capacity through Google-backed leases with "
                  "repurposed Bitcoin mining sites.",
         "domain": "energy", "actor": ["anthropic", "google"], "score": "2.3 GW",
         "evidences": ["burning-molecules-for-tokens"]},
        {"id": "2025-12-19-samsung-exynos-2600-2nm",
         "title": "Samsung ships the first 2-nm gate-all-around phone SoC",
         "claim": "Samsung unveiled the Exynos 2600, the first 2-nm gate-all-around smartphone "
                  "system-on-chip.",
         "domain": "compute", "actor": ["samsung"], "score": "2 nm"},
        {"id": "2025-12-19-space-superiority-lunar-reactor",
         "title": "A White House order demands a lunar surface reactor by 2030",
         "claim": "A White House executive order on Ensuring American Space Superiority requires "
                  "deployment of space nuclear power and a lunar surface reactor by 2030.",
         "domain": "space", "actor": ["white-house"], "score": "by 2030",
         "evidences": ["orbit-as-compute", "politics-as-infrastructure"]},
        {"id": "2025-12-19-artemis-ii-months-away",
         "title": "Artemis II is months from a human lunar flyby",
         "claim": "NASA administrator Jared Isaacman confirmed Artemis II is months away from "
                  "a crewed lunar flyby.",
         "domain": "space", "actor": ["nasa"],
         "supersedes": [B + "developments/2025-12-18-isaacman-nasa-project-athena"]},
        {"id": "2025-12-19-supersonic-aviation-act",
         "title": "The House legalizes overland supersonic flight",
         "claim": "The House passed the Supersonic Aviation Modernization Act, legalizing "
                  "overland supersonic flight provided the boom does not reach the ground.",
         "domain": "policy", "actor": ["us-congress"], "evidences": ["legislating-the-shift"]},
        {"id": "2025-12-19-trump-media-tae-fusion",
         "title": "Trump Media merges with fusion firm TAE in a $6B deal",
         "claim": "Trump Media is merging with fusion company TAE Technologies in a $6 billion "
                  "deal to build a utility-scale plant.",
         "domain": "energy", "actor": ["tae-technologies"], "score": "$6B",
         "evidences": ["industrialized-nature"]},
        {"id": "2025-12-19-openai-100b-at-830b",
         "title": "OpenAI raises $100B at an $830B valuation",
         "claim": "OpenAI is raising $100 billion at an $830 billion valuation on $19 billion "
                  "of annualized revenue.",
         "domain": "economics", "actor": ["openai"], "score": "$100B at $830B, $19B ARR",
         "evidences": ["compute-capital-stack"]},
        {"id": "2025-12-19-thinking-machines-50b",
         "title": "Thinking Machines discusses a $50B valuation",
         "claim": "Mira Murati's Thinking Machines is discussing a $50 billion valuation.",
         "domain": "economics", "actor": ["thinking-machines"], "score": "$50B"},
    ],
}
