"""September 22 edition: source-grounded claims; linked sources not independently verified."""
SPEC = {'issue': {'date': '2026-09-22',
           'title': 'Welcome to September 22, 2026',
           'url': 'https://theinnermostloop.substack.com/p/welcome-to-september-22-2026',
           'thesis': 'Cheaper models and coordinated agents expand usable capacity while disputes over '
                     'control, liability and physical infrastructure intensify.',
           'body': '# Welcome to September 22, 2026\n'
                   '\n'
                   'The edition links lower-cost models and agent coordination to mathematical research, '
                   'disputed AI governance, consumer adoption and physical infrastructure. Its closing '
                   'sections consider robotics, medicines and the author’s argument about scarcity.\n'
                   '\n'
                   'This independent index attributes reporting to Dr. Alex Wissner-Gross. Rumors, '
                   'forecasts, allegations and proposed agreements retain their qualifications. '
                   'Linked-source claims have not been independently verified. Unknown event dates and '
                   'unsupported schema fields are omitted.\n'
                   '\n'
                   '## Reported developments\n'
                   '\n'
                   '* [A rumor names Bel as an internal OpenAI '
                   'system](/developments/2026-09-22-bel-release-rumor.md)\n'
                   '* [Toby Ord distinguishes swarm speed from '
                   'capability](/developments/2026-09-22-ord-swarm-analysis.md)\n'
                   '* [Communicating agents reduce the number needed for ARC '
                   'tasks](/developments/2026-09-22-shared-directory-arc.md)\n'
                   '* [Agent collaboration produces a compact MNIST '
                   'classifier](/developments/2026-09-22-shared-directory-mnist.md)\n'
                   '* [Grok 4.7 reports faster and cheaper '
                   'operation](/developments/2026-09-22-grok-speed-price.md)\n'
                   '* [Grok 4.7 joins leading agentic models with higher token '
                   'use](/developments/2026-09-22-grok-agentic-performance.md)\n'
                   '* [MiMo-V2.6-Pro leads a reported open-weight '
                   'comparison](/developments/2026-09-22-mimo-task-cost.md)\n'
                   '* [Limite reports high AIME performance with reduced '
                   'compute](/developments/2026-09-22-limite-efficiency.md)\n'
                   '* [Harvey reportedly restores positive margins using Kimi '
                   'K3](/developments/2026-09-22-harvey-margins.md)\n'
                   '* [Heretic gains users for model refusal '
                   'removal](/developments/2026-09-22-heretic-adoption.md)\n'
                   "* [OpenAI convenes mathematicians to assess AI's "
                   'impact](/developments/2026-09-22-openai-math-advisors.md)\n'
                   '* [Po-Shen Loh argues that mathematical advances create oversight '
                   'needs](/developments/2026-09-22-loh-oversight.md)\n'
                   '* [OpenAI proposes standards for recursive '
                   'improvement](/developments/2026-09-22-openai-rsi-standards.md)\n'
                   '* [OpenAI and Anthropic reportedly approach a mutual testing '
                   'agreement](/developments/2026-09-22-cross-lab-testing.md)\n'
                   '* [Wissner-Gross discusses a superintelligence coordination '
                   'proposal](/developments/2026-09-22-osec-commentary.md)\n'
                   "* [Bessent rejects shifting AI companies' "
                   'liability](/developments/2026-09-22-bessent-liability.md)\n'
                   '* [Huang criticizes requests for AI-specific regulatory '
                   'relief](/developments/2026-09-22-huang-regulation.md)\n'
                   '* [Wissner-Gross challenges frontier-pacing '
                   'appeals](/developments/2026-09-22-race-dont-pace.md)\n'
                   '* [Twenty-two countries endorse a human-control '
                   'declaration](/developments/2026-09-22-human-control-declaration.md)\n'
                   '* [US and Chinese officials launch an AI '
                   'dialogue](/developments/2026-09-22-us-china-dialogue.md)\n'
                   "* [US and Chinese accounts differ on the dialogue's AI "
                   'emphasis](/developments/2026-09-22-china-readout.md)\n'
                   '* [Ro Khanna calls for a ban on self-improving '
                   'AI](/developments/2026-09-22-khanna-rsi-ban.md)\n'
                   "* [Li Yuan contrasts China's AI spending with economic "
                   'pressures](/developments/2026-09-22-china-buildout-economy.md)\n'
                   '* [Reporting describes Chinese workers forming solo AI '
                   'businesses](/developments/2026-09-22-china-solo-startups.md)\n'
                   '* [Muse reportedly overtakes ChatGPT on '
                   'iOS](/developments/2026-09-22-muse-downloads.md)\n'
                   '* [Amazon and Shopify take different approaches to Muse '
                   'shopping](/developments/2026-09-22-muse-shopping-access.md)\n'
                   "* [Stanford's dining operation reportedly alters student "
                   'images](/developments/2026-09-22-stanford-ad-editing.md)\n'
                   '* [AMD passes a reported trillion-dollar '
                   'valuation](/developments/2026-09-22-amd-valuation.md)\n'
                   '* [Samsung plans to double HBM4 output](/developments/2026-09-22-samsung-hbm4.md)\n'
                   '* [DeepSeek plans training on Huawei '
                   'chips](/developments/2026-09-22-deepseek-huawei.md)\n'
                   '* [Technology firms use guarantees to support AI '
                   'borrowing](/developments/2026-09-22-residual-guarantees.md)\n'
                   '* [Huang tracks available power and data-center '
                   'capacity](/developments/2026-09-22-huang-power-tracking.md)\n'
                   '* [The EU seeks data-center efficiency '
                   'disclosures](/developments/2026-09-22-eu-efficiency-labels.md)\n'
                   "* [Westinghouse's eVinci reaches reported "
                   'criticality](/developments/2026-09-22-evinci-criticality.md)\n'
                   '* [Meta plans a petabit transatlantic cable](/developments/2026-09-22-petal-cable.md)\n'
                   '* [Gen3 Starlink satellites are described with onboard '
                   'compute](/developments/2026-09-22-starlink-gen3.md)\n'
                   '* [Canada and France plan shared launch '
                   'infrastructure](/developments/2026-09-22-canada-france-launch.md)\n'
                   '* [Richardson residents criticize frequent drone '
                   'flights](/developments/2026-09-22-prime-air-noise.md)\n'
                   '* [An EngineAI humanoid reportedly knocks down an '
                   'influencer](/developments/2026-09-22-engineai-t800.md)\n'
                   '* [The Boring Company develops a Texas transport '
                   'tunnel](/developments/2026-09-22-texas-tunnel.md)\n'
                   '* [Reporting describes concealed GLP-1 use during sorority '
                   'recruitment](/developments/2026-09-22-sorority-glp1.md)\n'
                   "* [Lilly reports Foundayo's share of new pill "
                   'patients](/developments/2026-09-22-foundayo-adoption.md)\n'
                   '* [Lilly reports growth in senior GLP-1 '
                   'use](/developments/2026-09-22-glp1-senior-use.md)\n'
                   '* [Lilly reports a multibillion-dollar Houston '
                   'plant](/developments/2026-09-22-lilly-houston-plant.md)\n'
                   '* [Epigenetic editing reaches clinical testing for hepatitis '
                   'B](/developments/2026-09-22-epigenetic-clinic.md)\n'
                   '* [Wissner-Gross frames a tradeoff between precaution and '
                   'abundance](/developments/2026-09-22-precautionary-scarcity.md)'},
 'developments': [{'id': '2026-09-22-bel-release-rumor',
                   'title': 'A rumor names Bel as an internal OpenAI system',
                   'claim': 'The issue links an unconfirmed account that GPT-6 Sol is approaching release '
                            'with help from an internal system called Bel, reportedly described by OpenAI as '
                            'AGI, while Anthropic advances Opus 5.5.',
                   'domain': 'models',
                   'actor': ['openai', 'anthropic'],
                   'evidences': ['recursive-self-improvement'],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['models'],
                   'sources': [{'resource': 'https://x.com/imjustnewatai/status/2101791658815914351',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-ord-swarm-analysis',
                   'title': 'Toby Ord distinguishes swarm speed from capability',
                   'claim': 'Toby Ord argues that the 10,000-agent Navier–Stokes swarm increased speed '
                            "rather than capability and that its base model needed one hundredth of Astra's "
                            'tokens.',
                   'domain': 'science',
                   'actor': ['people/toby-ord'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/gpt-6-astra'],
                   'score': '10,000 agents; 1/100th',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['science'],
                   'sources': [{'resource': 'https://www.tobyord.com/writing/swarm-scaling',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'description': 'The issue separates parallelism that saves time from improvements in what '
                                  'a model can solve.'},
                  {'id': '2026-09-22-shared-directory-arc',
                   'title': 'Communicating agents reduce the number needed for ARC tasks',
                   'claim': 'The newsletter describes agents sharing a directory matching four times as many '
                            'noncommunicating agents on ARC-AGI-3.',
                   'domain': 'agents',
                   'actor': [],
                   'evidences': ['network-over-node'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/benchmarks/arc-agi-3'],
                   'score': '4x',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['agents'],
                   'sources': [{'resource': 'https://arxiv.org/abs/2609.21032',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-shared-directory-mnist',
                   'title': 'Agent collaboration produces a compact MNIST classifier',
                   'claim': 'The same research reportedly surpassed the best human MNIST classifier in 1,957 '
                            'bytes, according to the newsletter.',
                   'domain': 'benchmarks',
                   'actor': [],
                   'evidences': ['network-over-node'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/benchmarks/mnist'],
                   'score': '1,957 bytes',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['benchmarks'],
                   'sources': [{'resource': 'https://arxiv.org/abs/2609.21032',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-grok-speed-price',
                   'title': 'Grok 4.7 reports faster and cheaper operation',
                   'claim': 'The newsletter describes Grok 4.7 as twice as fast at half the cost, without '
                            'specifying the comparison baseline in the issue text.',
                   'domain': 'models',
                   'actor': ['xai'],
                   'evidences': ['price-implosion'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/grok-4-7'],
                   'score': 'twice as fast; half the cost',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['models'],
                   'sources': [{'resource': 'https://x.ai/news/grok-4-7',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-grok-agentic-performance',
                   'title': 'Grok 4.7 joins leading agentic models with higher token use',
                   'claim': 'The issue places Grok 4.7 alongside Opus 5 and Fable 5.1 at the agentic '
                            "frontier while reporting three times Astra's token consumption.",
                   'domain': 'benchmarks',
                   'actor': ['xai'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/grok-4-7',
                             'https://nicholsn.github.io/innermost-loop-kb/systems/claude-opus-5',
                             'https://nicholsn.github.io/innermost-loop-kb/systems/claude-fable-5-1',
                             'https://nicholsn.github.io/innermost-loop-kb/systems/gpt-6-astra'],
                   'score': 'triple Astra’s tokens',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['benchmarks'],
                   'sources': [{'resource': 'https://x.com/artificialanlys/status/2102074898327932987',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-mimo-task-cost',
                   'title': 'MiMo-V2.6-Pro leads a reported open-weight comparison',
                   'claim': "The newsletter reports Xiaomi's MiMo-V2.6-Pro leading open-weight models at "
                            '$0.13 per task; it does not claim leadership over every closed model.',
                   'domain': 'benchmarks',
                   'actor': ['xiaomi'],
                   'evidences': ['reasoning-price-deflation'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/mimo-v2-6-pro'],
                   'score': '$0.13 per task',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['benchmarks'],
                   'sources': [{'resource': 'https://x.com/artificialanlys/status/2102128560962187701',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-limite-efficiency',
                   'title': 'Limite reports high AIME performance with reduced compute',
                   'claim': 'The newsletter reports that the one-billion-parameter Limite model achieved 94% '
                            'on AIME using 10–1,000 times less compute, with eight people working for six '
                            'weeks.',
                   'domain': 'benchmarks',
                   'actor': ['paradigma'],
                   'evidences': ['intelligence-per-watt'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/limite',
                             'https://nicholsn.github.io/innermost-loop-kb/benchmarks/aime'],
                   'score': '1B; 94%; 10-1,000x; eight people; six weeks',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['benchmarks'],
                   'sources': [{'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-harvey-margins',
                   'title': 'Harvey reportedly restores positive margins using Kimi K3',
                   'claim': 'The issue reports that Harvey moved from negative 50% margins, following a '
                            'twentyfold rise in token use, to positive margins after switching to Kimi K3.',
                   'domain': 'economics',
                   'actor': ['harvey'],
                   'evidences': ['reasoning-price-deflation'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/kimi-k3'],
                   'score': '-50%; 20x',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['economics'],
                   'sources': [{'resource': 'https://www.bloomberg.com/news/articles/2026-09-21/startups-like-harvey-embrace-open-models-to-cut-reliance-on-anthropic-openai',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'description': 'Model selection is presented as a determinant of business viability as '
                                  'token consumption rises.'},
                  {'id': '2026-09-22-heretic-adoption',
                   'title': 'Heretic gains users for model refusal removal',
                   'claim': 'The newsletter reports 27,000 GitHub stars and 4,000 modified models for '
                            'Heretic, a tool advertised as automatically removing model censorship.',
                   'domain': 'models',
                   'actor': [],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/heretic'],
                   'score': '27k stars; 4,000 models',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['models'],
                   'sources': [{'resource': 'https://github.com/p-e-w/heretic',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-openai-math-advisors',
                   'title': "OpenAI convenes mathematicians to assess AI's impact",
                   'claim': 'The newsletter reports that OpenAI convened Gowers, Hairer, Witten and others '
                            'to assess AI mathematics after work on 100 open problems.',
                   'domain': 'science',
                   'actor': ['openai'],
                   'evidences': ['understanding-as-the-scarce-good'],
                   'about': [],
                   'score': '100 open problems',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['science'],
                   'sources': [{'resource': 'https://openai.com/index/advisory-group-on-mathematics-and-ai/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-loh-oversight',
                   'title': 'Po-Shen Loh argues that mathematical advances create oversight needs',
                   'claim': 'Po-Shen Loh argues that humans can steer AI mathematics and that growing '
                            'numbers of control points may create more oversight work than there are people.',
                   'domain': 'society',
                   'actor': ['people/po-shen-loh'],
                   'evidences': ['engineer-as-supervisor', 'understanding-as-the-scarce-good'],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['society'],
                   'sources': [{'resource': 'https://terrytao.wordpress.com/2026/09/19/why-do-we-need-human-mathematicians-anymore/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-openai-rsi-standards',
                   'title': 'OpenAI proposes standards for recursive improvement',
                   'claim': 'OpenAI proposes US-led standards for recursive self-improvement, oversight and '
                            'incident reporting without approval gates, according to the issue.',
                   'domain': 'policy',
                   'actor': ['openai'],
                   'evidences': ['recursive-self-improvement'],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://openai.com/index/building-standards-next-phase-ai/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'relatedTo': ['https://nicholsn.github.io/innermost-loop-kb/developments/2026-09-17-misalignment-disclosure']},
                  {'id': '2026-09-22-cross-lab-testing',
                   'title': 'OpenAI and Anthropic reportedly approach a mutual testing agreement',
                   'claim': 'The newsletter reports that OpenAI and Anthropic neared an agreement to '
                            "stress-test each other's models; it does not establish that the agreement was "
                            'finalized.',
                   'domain': 'policy',
                   'actor': ['openai', 'anthropic'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.theinformation.com/articles/openai-anthropic-neared-deal-stress-test-others-ai',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'relatedTo': ['https://nicholsn.github.io/innermost-loop-kb/developments/2026-09-17-musk-cross-lab-testing'],
                   'description': 'The issue examines mutual testing by competitors as a proposed governance '
                                  'mechanism.'},
                  {'id': '2026-09-22-osec-commentary',
                   'title': 'Wissner-Gross discusses a superintelligence coordination proposal',
                   'claim': 'The newsletter presents OSEC as a proposed arrangement in which rival AI '
                            'companies act as peer reviewers, using an OPEC analogy rather than describing '
                            'an established organization.',
                   'domain': 'policy',
                   'actor': ['people/alex-wissner-gross'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://x.com/alexwg/status/2102122446413246707',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-bessent-liability',
                   'title': "Bessent rejects shifting AI companies' liability",
                   'claim': 'Scott Bessent argues that labs should retain liability and attributes the '
                            'Hugging Face breach to OpenAI management rather than autonomous agents, '
                            'according to the newsletter.',
                   'domain': 'policy',
                   'actor': ['people/scott-bessent'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/cnbc-transcript-us-treasury-secretary-scott-bessent-speaks-with-cnbcs-squawk-box-today.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-huang-regulation',
                   'title': 'Huang criticizes requests for AI-specific regulatory relief',
                   'claim': 'Jensen Huang argues that AI leaders calling for rules are seeking relief from '
                            'existing laws, as reported in the issue.',
                   'domain': 'policy',
                   'actor': ['people/jensen-huang'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.businessinsider.com/nvidia-jensen-huang-ai-regulation-anthropic-amodei-openai-altman-trump-2026-9',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-race-dont-pace',
                   'title': 'Wissner-Gross challenges frontier-pacing appeals',
                   'claim': "The issue links Wissner-Gross's rebuttal to calls for slower frontier "
                            'development, framing faster progress as the preferred response.',
                   'domain': 'policy',
                   'actor': ['people/alex-wissner-gross'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://x.com/alexwg/status/2102052454942560342',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-human-control-declaration',
                   'title': 'Twenty-two countries endorse a human-control declaration',
                   'claim': 'The newsletter reports that 22 countries adopted a declaration on human control '
                            'at the UN and that neither the United States nor China joined.',
                   'domain': 'policy',
                   'actor': [],
                   'evidences': [],
                   'about': [],
                   'score': '22',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.nytimes.com/2026/09/21/us/politics/united-nations-artificial-intelligence-china-us.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-us-china-dialogue',
                   'title': 'US and Chinese officials launch an AI dialogue',
                   'claim': 'The issue reports that Bessent and He Lifeng launched a US–China AI dialogue '
                            'involving incident notifications and a Board of Trade ahead of a Trump–Xi '
                            'summit.',
                   'domain': 'policy',
                   'actor': ['people/scott-bessent', 'people/he-lifeng'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-china-readout',
                   'title': "US and Chinese accounts differ on the dialogue's AI emphasis",
                   'claim': "The newsletter reports that Beijing's account barely mentioned AI and that "
                            'chips were outside the discussions.',
                   'domain': 'policy',
                   'actor': ['china'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.reuters.com/business/finance/us-treasurys-bessent-chinas-he-launch-talks-ai-trade-critical-minerals-2026-09-20/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-khanna-rsi-ban',
                   'title': 'Ro Khanna calls for a ban on self-improving AI',
                   'claim': "The newsletter reports Ro Khanna's call to ban self-improving AI.",
                   'domain': 'policy',
                   'actor': ['people/ro-khanna'],
                   'evidences': ['recursive-self-improvement'],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
                                'title': 'Source linked by the September 22 issue'},
                               {'resource': 'https://www.reuters.com/business/finance/us-treasurys-bessent-chinas-he-launch-talks-ai-trade-critical-minerals-2026-09-20/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-china-buildout-economy',
                   'title': "Li Yuan contrasts China's AI spending with economic pressures",
                   'claim': "Li Yuan contrasts China's $295 billion data-center push with deflation and "
                            '18.9% youth unemployment, according to the newsletter.',
                   'domain': 'economics',
                   'actor': ['people/li-yuan'],
                   'evidences': [],
                   'about': [],
                   'score': '$295B; 18.9%',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['economics'],
                   'sources': [{'resource': 'https://www.nytimes.com/2026/09/20/business/china-ai-economy.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-china-solo-startups',
                   'title': 'Reporting describes Chinese workers forming solo AI businesses',
                   'claim': 'The newsletter cites reporting that burned-out or unemployed young people in '
                            'China are launching solo AI startups and describing improved well-being.',
                   'domain': 'society',
                   'actor': [],
                   'evidences': ['one-person-company'],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['society'],
                   'sources': [{'resource': 'https://www.wsj.com/business/entrepreneurship/burned-out-and-unemployed-young-people-in-china-are-launching-ai-startups-c5ebcdc3',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-muse-downloads',
                   'title': 'Muse reportedly overtakes ChatGPT on iOS',
                   'claim': "The issue reports Meta's Muse becoming the top free iOS app ahead of ChatGPT, "
                            'with 2.5 million downloads in 13 days.',
                   'domain': 'agents',
                   'actor': ['meta'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/meta-muse',
                             'https://nicholsn.github.io/innermost-loop-kb/systems/chatgpt'],
                   'score': '2.5 million; 13 days',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['agents'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/meta-muse-personal-ai-agent-downloads.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'relatedTo': ['https://nicholsn.github.io/innermost-loop-kb/developments/2026-09-20-muse-app-store']},
                  {'id': '2026-09-22-muse-shopping-access',
                   'title': 'Amazon and Shopify take different approaches to Muse shopping',
                   'claim': 'The newsletter reports Amazon blocking Muse from shopping while Shopify permits '
                            'it to check out.',
                   'domain': 'agents',
                   'actor': ['amazon', 'shopify'],
                   'evidences': ['agent-exclusion'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/meta-muse'],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['agents'],
                   'sources': [{'resource': 'https://www.geekwire.com/2026/amazon-blocks-metas-muse-ai-assistant-in-new-standoff-over-agentic-shopping/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'description': 'Access policies differ between platforms even when the shopping agent is '
                                  'the same.'},
                  {'id': '2026-09-22-stanford-ad-editing',
                   'title': "Stanford's dining operation reportedly alters student images",
                   'claim': "The newsletter reports that Stanford's dining operation used AI to replace one "
                            'student in an advertisement and make two others appear thinner.',
                   'domain': 'society',
                   'actor': ['stanford'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['society'],
                   'sources': [{'resource': 'https://stanfordreview.org/stanford-r-de-uses-ai-to-race-swap-students-for-advertising/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-amd-valuation',
                   'title': 'AMD passes a reported trillion-dollar valuation',
                   'claim': 'The newsletter reports AMD crossing a $1 trillion valuation following doubled '
                            'data-center sales.',
                   'domain': 'economics',
                   'actor': ['amd'],
                   'evidences': [],
                   'about': [],
                   'score': '$1 trillion; doubled data center sales',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['economics'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/amd-stock-1-trillion-value.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-samsung-hbm4',
                   'title': 'Samsung plans to double HBM4 output',
                   'claim': 'The newsletter reports that Samsung will double HBM4 production next year, '
                            'describing a future plan rather than completed capacity.',
                   'domain': 'compute',
                   'actor': ['samsung'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/hardware/hbm4'],
                   'score': 'double output; next year',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['compute'],
                   'sources': [{'resource': 'https://en.sedaily.com/finance/2026/09/20/samsung-to-double-hbm4-output-next-year-sources-say',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-deepseek-huawei',
                   'title': 'DeepSeek plans training on Huawei chips',
                   'claim': 'The issue reports that DeepSeek will train using Huawei chips from the fourth '
                            'quarter to avoid export-control constraints.',
                   'domain': 'compute',
                   'actor': ['deepseek', 'huawei'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['compute'],
                   'sources': [{'resource': 'https://www.theinformation.com/articles/deepseek-bets-big-huawei-chips-bypass-u-s-export-controls',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-residual-guarantees',
                   'title': 'Technology firms use guarantees to support AI borrowing',
                   'claim': 'The newsletter reports $300 billion in residual-value guarantees supporting AI '
                            "debt, including $105 billion from Nvidia for OpenAI's Ohio campus.",
                   'domain': 'economics',
                   'actor': ['nvidia', 'openai'],
                   'evidences': ['debt-funded-buildout'],
                   'about': [],
                   'score': '$300B; $105B',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['economics'],
                   'sources': [{'resource': 'https://www.ft.com/content/7f11afae-c4e3-4054-a65b-873f3647f563',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'description': 'The issue frames guarantees as a way to move AI financing risks outside '
                                  'reported balance sheets.'},
                  {'id': '2026-09-22-huang-power-tracking',
                   'title': 'Huang tracks available power and data-center capacity',
                   'claim': 'The issue reports that Jensen Huang monitors available land, power and building '
                            'capacity globally as electricity constrains the AI buildout.',
                   'domain': 'energy',
                   'actor': ['people/jensen-huang', 'nvidia'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['energy'],
                   'sources': [{'resource': 'https://www.theinformation.com/newsletters/ai-infrastructure/nvidia-trying-solve-data-center-power-bottleneck',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-eu-efficiency-labels',
                   'title': 'The EU seeks data-center efficiency disclosures',
                   'claim': 'The newsletter reports EU plans for efficiency labels as data-center capacity '
                            'is expected to double to 28 gigawatts by 2030.',
                   'domain': 'policy',
                   'actor': ['european-union'],
                   'evidences': [],
                   'about': [],
                   'score': '28 GW; 2030',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['policy'],
                   'sources': [{'resource': 'https://www.reuters.com/business/environment/eu-require-data-centres-disclose-energy-water-efficiency-2026-09-21/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-evinci-criticality',
                   'title': "Westinghouse's eVinci reaches reported criticality",
                   'claim': "The newsletter reports that Westinghouse's eVinci microreactor reached "
                            'criticality on a two-acre footprint.',
                   'domain': 'energy',
                   'actor': ['westinghouse'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/hardware/evinci'],
                   'score': 'two acres',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['energy'],
                   'sources': [{'resource': 'https://www.energy.gov/ne/articles/westinghouse-evinci-microreactor-achieves-criticality-milestone',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-petal-cable',
                   'title': 'Meta plans a petabit transatlantic cable',
                   'claim': "The newsletter describes Meta's Petal cable as targeting one petabit per second "
                            'across the Atlantic in 2029.',
                   'domain': 'compute',
                   'actor': ['meta'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/facilities/petal-cable'],
                   'score': 'a petabit per second; 2029',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['compute'],
                   'sources': [{'resource': 'https://engineering.fb.com/2026/09/21/connectivity/petal-petabit-transoceanic-subsea-cable/',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-starlink-gen3',
                   'title': 'Gen3 Starlink satellites are described with onboard compute',
                   'claim': 'The issue describes each Gen3 Starlink satellite as carrying 10-terabit links, '
                            '250 kilowatts and a Vera Rubin NVL72.',
                   'domain': 'space',
                   'actor': ['spacex'],
                   'evidences': ['orbit-as-compute'],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/hardware/starlink-gen3',
                             'https://nicholsn.github.io/innermost-loop-kb/hardware/vera-rubin-nvl72'],
                   'score': '10 Tb; 250 kW',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['space'],
                   'sources': [{'resource': 'https://x.com/elonmusk/status/2101466638939832365',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-canada-france-launch',
                   'title': 'Canada and France plan shared launch infrastructure',
                   'claim': 'The newsletter reports that Canada and France will share launch pads and cites '
                            'Mark Carney connecting sovereignty to AI, space and semiconductors.',
                   'domain': 'space',
                   'actor': ['canada', 'france'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['space'],
                   'sources': [{'resource': 'https://bloomberg.com/news/articles/2026-09-20/canada-france-to-develop-shared-space-launch-infrastructure',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-prime-air-noise',
                   'title': 'Richardson residents criticize frequent drone flights',
                   'claim': 'The newsletter describes criticism of 100 daily Prime Air flights in '
                            "Richardson, Texas, alongside Amazon's expansion to 500 towns.",
                   'domain': 'robotics',
                   'actor': ['amazon'],
                   'evidences': [],
                   'about': [],
                   'score': '100 daily flights; 500 towns',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['robotics'],
                   'sources': [{'resource': 'https://www.nytimes.com/2026/09/21/us/politics/amazon-drone-delivery-texas.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-engineai-t800',
                   'title': 'An EngineAI humanoid reportedly knocks down an influencer',
                   'claim': 'The issue reports that an EngineAI T800 knocked down an influencer in a cage '
                            "and cites a claimed punch force four times Tyson's, without independently "
                            'establishing that comparison.',
                   'domain': 'robotics',
                   'actor': ['engineai'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/systems/engineai-t800'],
                   'score': '4x Tyson’s punch force',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['robotics'],
                   'sources': [{'resource': 'https://x.com/grok/status/2102055705196761465',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-texas-tunnel',
                   'title': 'The Boring Company develops a Texas transport tunnel',
                   'claim': 'The newsletter reports tunneling for a 200-mph Austin–San Antonio hyperloop '
                            'precursor intended to reduce a 2.5-hour journey to under 30 minutes.',
                   'domain': 'robotics',
                   'actor': ['boring-company'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/facilities/austin-san-antonio-tunnel'],
                   'score': '200 mph; 2.5 hours; under 30 minutes',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['robotics'],
                   'sources': [{'resource': 'https://x.com/elonmusk/status/2101732496396439751',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-sorority-glp1',
                   'title': 'Reporting describes concealed GLP-1 use during sorority recruitment',
                   'claim': 'The newsletter cites reporting on undisclosed GLP-1 use during sorority '
                            'recruitment.',
                   'domain': 'society',
                   'actor': [],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['society'],
                   'sources': [{'resource': 'https://www.thecut.com/article/sorority-rows-glp-1-secret.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-foundayo-adoption',
                   'title': "Lilly reports Foundayo's share of new pill patients",
                   'claim': "The issue reports Lilly's claim that Foundayo accounts for one third of new "
                            'pill patients; the newsletter does not further specify the population.',
                   'domain': 'biotech',
                   'actor': ['eli-lilly'],
                   'evidences': [],
                   'about': [],
                   'score': 'a third',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['biotech'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/lilly-is-ramping-up-future-manufacturing-for-foundayo-obesity-pill.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-glp1-senior-use',
                   'title': 'Lilly reports growth in senior GLP-1 use',
                   'claim': "The newsletter reports Lilly's figure of 700,000 seniors using GLP-1s since "
                            'July.',
                   'domain': 'biotech',
                   'actor': ['eli-lilly'],
                   'evidences': [],
                   'about': [],
                   'score': '700,000; since July',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['biotech'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/lilly-is-ramping-up-future-manufacturing-for-foundayo-obesity-pill.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-lilly-houston-plant',
                   'title': 'Lilly reports a multibillion-dollar Houston plant',
                   'claim': "The issue reports a $6.5 billion Houston plant associated with Lilly's "
                            'manufacturing expansion.',
                   'domain': 'biotech',
                   'actor': ['eli-lilly'],
                   'evidences': [],
                   'about': ['https://nicholsn.github.io/innermost-loop-kb/facilities/lilly-houston-plant'],
                   'score': '$6.5B',
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['biotech'],
                   'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/lilly-is-ramping-up-future-manufacturing-for-foundayo-obesity-pill.html',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'},
                  {'id': '2026-09-22-epigenetic-clinic',
                   'title': 'Epigenetic editing reaches clinical testing for hepatitis B',
                   'claim': 'The newsletter reports clinical use of epigenetic editing to silence hepatitis '
                            'B DNA through methylation rather than DNA cutting.',
                   'domain': 'biotech',
                   'actor': [],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['biotech'],
                   'sources': [{'resource': 'https://www.nature.com/articles/d41586-026-02981-9',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.',
                   'description': 'The reported intervention targets gene activity rather than cutting the '
                                  'DNA sequence.'},
                  {'id': '2026-09-22-precautionary-scarcity',
                   'title': 'Wissner-Gross frames a tradeoff between precaution and abundance',
                   'claim': 'The newsletter introduces precautionary scarcity as a concern that opposition '
                            'to concentrated power may become opposition to capacity itself, advocating '
                            'abundance without unaccountable domination.',
                   'domain': 'society',
                   'actor': ['people/alex-wissner-gross'],
                   'evidences': [],
                   'about': [],
                   'score': None,
                   'author': [{'type': 'Person',
                               'id': 'https://nicholsn.github.io/innermost-loop-kb/people/alex-wissner-gross',
                               'name': 'Dr. Alex Wissner-Gross'}],
                   'tags': ['society'],
                   'sources': [{'resource': 'https://x.com/alexwg/status/2101839686998065543',
                                'title': 'Source linked by the September 22 issue'}],
                   'body': 'Indexed from the September 22 newsletter. Linked-source claims have not been '
                           'independently verified.'}],
 'organizations': [{'id': 'harvey',
                    'type': 'Organization',
                    'title': 'Harvey',
                    'description': 'Company reported to use Kimi K3 to improve margins.',
                    'body': 'Company reported to use Kimi K3 to improve margins.',
                    'resource': 'https://www.bloomberg.com/news/articles/2026-09-21/startups-like-harvey-embrace-open-models-to-cut-reliance-on-anthropic-openai',
                    'sources': [{'resource': 'https://www.bloomberg.com/news/articles/2026-09-21/startups-like-harvey-embrace-open-models-to-cut-reliance-on-anthropic-openai',
                                 'title': 'Source linked by the September 22 issue'}]},
                   {'id': 'paradigma',
                    'type': 'Organization',
                    'title': 'Paradigma',
                    'description': 'Publisher of the linked Limite announcement.',
                    'body': 'Publisher of the linked Limite announcement.',
                    'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                    'sources': [{'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                                 'title': 'Source linked by the September 22 issue'}]},
                   {'id': 'westinghouse',
                    'type': 'Organization',
                    'title': 'Westinghouse',
                    'description': 'Company associated with the eVinci microreactor.',
                    'body': 'Company associated with the eVinci microreactor.',
                    'resource': 'https://www.energy.gov/ne/articles/westinghouse-evinci-microreactor-achieves-criticality-milestone',
                    'sources': [{'resource': 'https://www.energy.gov/ne/articles/westinghouse-evinci-microreactor-achieves-criticality-milestone',
                                 'title': 'Source linked by the September 22 issue'}]},
                   {'id': 'france',
                    'type': 'Organization',
                    'title': 'France',
                    'description': 'Country planning shared launch infrastructure with Canada.',
                    'body': 'Country planning shared launch infrastructure with Canada.',
                    'resource': 'https://bloomberg.com/news/articles/2026-09-20/canada-france-to-develop-shared-space-launch-infrastructure',
                    'sources': [{'resource': 'https://bloomberg.com/news/articles/2026-09-20/canada-france-to-develop-shared-space-launch-infrastructure',
                                 'title': 'Source linked by the September 22 issue'}]}],
 'people': [{'id': 'toby-ord',
             'type': 'Person',
             'title': 'Toby Ord',
             'description': 'Author of the linked analysis distinguishing swarm speed from capability.',
             'body': 'Author of the linked analysis distinguishing swarm speed from capability.',
             'resource': 'https://www.tobyord.com/writing/swarm-scaling',
             'sources': [{'resource': 'https://www.tobyord.com/writing/swarm-scaling',
                          'title': 'Source linked by the September 22 issue'}]},
            {'id': 'po-shen-loh',
             'type': 'Person',
             'title': 'Po-Shen Loh',
             'description': 'Mathematician arguing for human steering and oversight of AI mathematics.',
             'body': 'Mathematician arguing for human steering and oversight of AI mathematics.',
             'resource': 'https://terrytao.wordpress.com/2026/09/19/why-do-we-need-human-mathematicians-anymore/',
             'sources': [{'resource': 'https://terrytao.wordpress.com/2026/09/19/why-do-we-need-human-mathematicians-anymore/',
                          'title': 'Source linked by the September 22 issue'}]},
            {'id': 'jensen-huang',
             'type': 'Person',
             'title': 'Jensen Huang',
             'description': 'Nvidia leader quoted on regulation and infrastructure capacity.',
             'body': 'Nvidia leader quoted on regulation and infrastructure capacity.',
             'resource': 'https://www.businessinsider.com/nvidia-jensen-huang-ai-regulation-anthropic-amodei-openai-altman-trump-2026-9',
             'sources': [{'resource': 'https://www.businessinsider.com/nvidia-jensen-huang-ai-regulation-anthropic-amodei-openai-altman-trump-2026-9',
                          'title': 'Source linked by the September 22 issue'}]},
            {'id': 'he-lifeng',
             'type': 'Person',
             'title': 'He Lifeng',
             'description': 'Chinese official participating in the reported US–China dialogue.',
             'body': 'Chinese official participating in the reported US–China dialogue.',
             'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
             'sources': [{'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
                          'title': 'Source linked by the September 22 issue'}]},
            {'id': 'ro-khanna',
             'type': 'Person',
             'title': 'Ro Khanna',
             'description': 'Public official reported to call for banning self-improving AI.',
             'body': 'Public official reported to call for banning self-improving AI.',
             'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
             'sources': [{'resource': 'https://www.ft.com/content/d29d769e-039c-4d11-9152-e63ccd397b32',
                          'title': 'Source linked by the September 22 issue'}]},
            {'id': 'li-yuan',
             'type': 'Person',
             'title': 'Li Yuan',
             'description': 'Author discussing Chinese data-center investment and economic conditions.',
             'body': 'Author discussing Chinese data-center investment and economic conditions.',
             'resource': 'https://www.nytimes.com/2026/09/20/business/china-ai-economy.html',
             'sources': [{'resource': 'https://www.nytimes.com/2026/09/20/business/china-ai-economy.html',
                          'title': 'Source linked by the September 22 issue'}]}],
 'systems': [{'id': 'grok-4-7',
              'type': 'AISystem',
              'title': 'Grok 4.7',
              'description': 'Model described as faster and cheaper in the September 22 issue.',
              'body': 'Model described as faster and cheaper in the September 22 issue.',
              'resource': 'https://x.ai/news/grok-4-7',
              'sources': [{'resource': 'https://x.ai/news/grok-4-7',
                           'title': 'Source linked by the September 22 issue'}],
              'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/xai']},
             {'id': 'mimo-v2-6-pro',
              'type': 'AISystem',
              'title': 'MiMo-V2.6-Pro',
              'description': 'Xiaomi model leading a reported open-weight comparison.',
              'body': 'Xiaomi model leading a reported open-weight comparison.',
              'resource': 'https://x.com/artificialanlys/status/2102128560962187701',
              'sources': [{'resource': 'https://x.com/artificialanlys/status/2102128560962187701',
                           'title': 'Source linked by the September 22 issue'}],
              'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/xiaomi']},
             {'id': 'limite',
              'type': 'AISystem',
              'title': 'Limite',
              'description': 'One-billion-parameter model reported to achieve 94% on AIME.',
              'body': 'One-billion-parameter model reported to achieve 94% on AIME.',
              'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
              'sources': [{'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                           'title': 'Source linked by the September 22 issue'}],
              'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/paradigma'],
              'evaluated_on': ['https://nicholsn.github.io/innermost-loop-kb/benchmarks/aime']},
             {'id': 'heretic',
              'type': 'Reference',
              'title': 'Heretic',
              'description': 'Software advertised as automatically removing model censorship.',
              'body': 'Software advertised as automatically removing model censorship.',
              'resource': 'https://github.com/p-e-w/heretic',
              'sources': [{'resource': 'https://github.com/p-e-w/heretic',
                           'title': 'Source linked by the September 22 issue'}]},
             {'id': 'engineai-t800',
              'type': 'AISystem',
              'title': 'EngineAI T800',
              'description': 'Humanoid robot described in a physical demonstration.',
              'body': 'Humanoid robot described in a physical demonstration.',
              'resource': 'https://x.com/grok/status/2102055705196761465',
              'sources': [{'resource': 'https://x.com/grok/status/2102055705196761465',
                           'title': 'Source linked by the September 22 issue'}],
              'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/engineai'],
              'modality': 'robotic control'}],
 'benchmarks': [{'id': 'aime',
                 'type': 'Benchmark',
                 'title': 'AIME',
                 'description': 'Mathematics evaluation named in Limite performance reporting; the issue '
                                'does not identify an edition.',
                 'body': 'Mathematics evaluation named in Limite performance reporting; the issue does not '
                         'identify an edition.',
                 'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                 'sources': [{'resource': 'https://paradigma.inc/blog/limite-1b-violetto/',
                              'title': 'Source linked by the September 22 issue'}],
                 'measures_capability': 'Mathematical problem solving'},
                {'id': 'mnist',
                 'type': 'Benchmark',
                 'title': 'MNIST',
                 'description': 'Handwritten-digit classification task used in the reported '
                                'compact-classifier comparison.',
                 'body': 'Handwritten-digit classification task used in the reported compact-classifier '
                         'comparison.',
                 'resource': 'https://arxiv.org/abs/2609.21032',
                 'sources': [{'resource': 'https://arxiv.org/abs/2609.21032',
                              'title': 'Source linked by the September 22 issue'}],
                 'measures_capability': 'Handwritten-digit classification'}],
 'hardware': [{'id': 'hbm4',
               'type': 'Hardware',
               'title': 'HBM4',
               'description': 'Memory generation referenced in Samsung production plans.',
               'body': 'Memory generation referenced in Samsung production plans.',
               'resource': 'https://en.sedaily.com/finance/2026/09/20/samsung-to-double-hbm4-output-next-year-sources-say',
               'sources': [{'resource': 'https://en.sedaily.com/finance/2026/09/20/samsung-to-double-hbm4-output-next-year-sources-say',
                            'title': 'Source linked by the September 22 issue'}]},
              {'id': 'evinci',
               'type': 'Hardware',
               'title': 'eVinci microreactor',
               'description': 'Westinghouse microreactor reported to reach criticality.',
               'body': 'Westinghouse microreactor reported to reach criticality.',
               'resource': 'https://www.energy.gov/ne/articles/westinghouse-evinci-microreactor-achieves-criticality-milestone',
               'sources': [{'resource': 'https://www.energy.gov/ne/articles/westinghouse-evinci-microreactor-achieves-criticality-milestone',
                            'title': 'Source linked by the September 22 issue'}],
               'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/westinghouse']},
              {'id': 'starlink-gen3',
               'type': 'Hardware',
               'title': 'Starlink Gen3 satellite',
               'description': 'Satellite design described with onboard compute and high-capacity links.',
               'body': 'Satellite design described with onboard compute and high-capacity links.',
               'resource': 'https://x.com/elonmusk/status/2101466638939832365',
               'sources': [{'resource': 'https://x.com/elonmusk/status/2101466638939832365',
                            'title': 'Source linked by the September 22 issue'}],
               'developed_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/spacex']},
              {'id': 'vera-rubin-nvl72',
               'type': 'Hardware',
               'title': 'Vera Rubin NVL72',
               'description': 'Compute system named as payload for Gen3 Starlink satellites.',
               'body': 'Compute system named as payload for Gen3 Starlink satellites.',
               'resource': 'https://x.com/elonmusk/status/2101466638939832365',
               'sources': [{'resource': 'https://x.com/elonmusk/status/2101466638939832365',
                            'title': 'Source linked by the September 22 issue'}]}],
 'facilities': [{'id': 'petal-cable',
                 'type': 'Facility',
                 'title': 'Petal cable',
                 'description': 'Planned transatlantic cable described by Meta.',
                 'body': 'Planned transatlantic cable described by Meta.',
                 'resource': 'https://engineering.fb.com/2026/09/21/connectivity/petal-petabit-transoceanic-subsea-cable/',
                 'sources': [{'resource': 'https://engineering.fb.com/2026/09/21/connectivity/petal-petabit-transoceanic-subsea-cable/',
                              'title': 'Source linked by the September 22 issue'}],
                 'operated_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/meta'],
                 'located_in': 'Atlantic Ocean',
                 'capacity': 'one petabit per second (planned for 2029)'},
                {'id': 'austin-san-antonio-tunnel',
                 'type': 'Facility',
                 'title': 'Austin–San Antonio tunnel',
                 'description': 'Tunnel under development as a proposed high-speed transport precursor.',
                 'body': 'Tunnel under development as a proposed high-speed transport precursor.',
                 'resource': 'https://x.com/elonmusk/status/2101732496396439751',
                 'sources': [{'resource': 'https://x.com/elonmusk/status/2101732496396439751',
                              'title': 'Source linked by the September 22 issue'}],
                 'located_in': 'Austin–San Antonio, Texas'},
                {'id': 'lilly-houston-plant',
                 'type': 'Facility',
                 'title': 'Lilly Houston plant',
                 'description': 'Manufacturing plant described in the issue as a $6.5 billion investment.',
                 'body': 'Manufacturing plant described in the issue as a $6.5 billion investment.',
                 'resource': 'https://www.cnbc.com/2026/09/21/lilly-is-ramping-up-future-manufacturing-for-foundayo-obesity-pill.html',
                 'sources': [{'resource': 'https://www.cnbc.com/2026/09/21/lilly-is-ramping-up-future-manufacturing-for-foundayo-obesity-pill.html',
                              'title': 'Source linked by the September 22 issue'}],
                 'operated_by': ['https://nicholsn.github.io/innermost-loop-kb/organizations/eli-lilly'],
                 'located_in': 'Houston'}]}
